### ISSUE TITLE
Testing Party Issue - Can't Sign Up

### ISSUE THREAD

**Issue by sjeremycohen** [gcivil-nyu-org/team-5-inperson#160]
Environment Information:
**OS** Windows 11
**Browser** - Brave 1.45.127 Chromium 107.0.5304.110 (Extensions Disabled - Private Browser Window)

**Reproduction Steps**

1. Navigate to user signup
2. Attempt to sign up (my credentials tested below)
3. Click the sign up button

username: sc8762@nyu.edu
email: sc8762@nyu.edu
password: 123123123-

**Error Encountered**
Nothing happens, can't log in with creds.

**Comment by as14680** [comment]
Hi,
Did you tried on staging or production env. link ? We are currently working on staging env. so signup functionality has been affected for the time being. Try on production link and let us know if that's still the case...
Thanks,
Akshat
