### ISSUE TITLE
Testing Party Issue - Simultaneous Logins Not Permitted

### ISSUE THREAD

**Issue by sjeremycohen** [gcivil-nyu-org/team-5-inperson#161]
Environment Information:
**OS** Windows 11
**Browser** - Brave 1.45.127 Chromium 107.0.5304.110 (Extensions Disabled - Private Browser Window)
**Credential Used** - user5@test.com

**Reproduction Steps** (This one may not be simple to reproduce)
1. Attempt to login as test5@gmail.com (I assume someone else is already logged in as this)

**Error Encountered**
User already logged in. (Login denied)

**Additional Notes**
If this is expected functionality, it shouldn't be. I have a phone, a laptop, and a desktop. If I use an app heavily, I should be able to simultaneously log in on all of them

**Comment by ds6332** [comment]
Thank you Scott. This is not  an expected functionality. We have identified it as a bug and will get to it soon.
