### ISSUE TITLE
Testing Party Issue - Long reviews cannot be saved

### ISSUE THREAD

**Issue by simaoalicechen** [gcivil-nyu-org/team-5-inperson#170]
Hello, 

I tried to leave a long comment to a bench -- " Alice is testing. She is trying to see if a lot of chars would break this review section. We will see how many words we can add here.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. " And the review is submitted successfully, but when I went back to the bench, it says it does not have reviews. 

![Screen Shot 2022-11-19 at 4.02.45 PM.png](https://images.zenhubusercontent.com/632e1cc1e96628897fa68160/9d17a1c8-474a-47d6-ac99-32915ba3ee30)

![Screen Shot 2022-11-19 at 4.02.56 PM.png](https://images.zenhubusercontent.com/632e1cc1e96628897fa68160/f97f95f6-5279-4b56-9de6-23ccb9590e3f)

**Comment by guptaviha** [comment]
Marking this is a duplicate issue and closing it

**Comment by simaoalicechen** [comment]
This should not be a duplicate issue. I think I was the first person to point out this bug. The previous bugs were different

**Comment by guptaviha** [comment]
Thanks for reporting this bug to us. The bug has been resolved

**Comment by simaoalicechen** [comment]
Would this be considered as kudos? Can you please let the TA know? Thanks
