### ISSUE TITLE
No help text to view what`s wrong during sign up

### ISSUE THREAD

**Issue by Pankhurinyu** [gcivil-nyu-org/team-5-inperson#173]
If I am trying to create a new account, and for whatever reason it does not get accepted by the system. I do not have any help text which can help me getting to know where I am doing wrong.  For example, I was not able to create an account and I did not know which field of mine was wrong.

https://user-images.githubusercontent.com/90795848/202878230-11df963b-d765-4289-b313-9d3514c12b26.mp4

**Comment by guptaviha** [comment]
Related to Issue "Testing Party: No minimum length for passwords#171". Fixed in latest release. Closing this.
