### ISSUE TITLE
Init deploy to integration

### ISSUE THREAD

**Issue by guptaviha** [gcivil-nyu-org/team-5-inperson#73]
**Problem Statement**
Deploying the frontend and backend app to AWS Amplify for Initial deployment to Staging environment

**Definition of Done**

- Connecting Github for continuous FE and BE update

- Successfully deploying server on AWS

- Site operational on the AWS link

- Test cases if any

**Helpful Link**

https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/

https://www.youtube.com/watch?v=xT2OhBTjZDY&t=132s

https://docs.aws.amazon.com/amplify/latest/userguide/deploy-backend.html

**Comment by as14680** [comment]
Application Live at EBS :- http://nyc5.ml/
